{
 "title": "Lobbyregister - City Monitor",
 "tags": [ "portfolio-4" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "postgres" },
   {
    "name": "City",
    "label": "Stadt / Ort",
    "query": "SELECT DISTINCT city FROM address WHERE city IS NOT NULL ORDER BY city;"
   }
  ]
 },
 "panels": [
  {
   "title": "Anzahl Lobbyisten in der Stadt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT re.id) as \"Anzahl Lobbyisten\"\nFROM register_entry re\nJOIN lobbyist_identity li ON re.id = li.entry_id\nJOIN address a ON li.address_id = a.id\nWHERE a.city IN (${City:sqlstring})"
    }
   ]
  },
  {
   "title": "Finanzkraft der Stadt (Lobby-Budget)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(fe.expenses_to_eur) as \"Finanzkraft (Total)\"\nFROM register_entry re\nJOIN lobbyist_identity li ON re.id = li.entry_id\nJOIN address a ON li.address_id = a.id\nJOIN financial_expenses fe ON re.id = fe.entry_id\nWHERE a.city IN (${City:sqlstring})"
    }
   ]
  },
  {
   "title": "Top Themen in dieser Stadt",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n    cl.de as \"Thema\", \n    COUNT(*) as \"Anzahl\"\nFROM register_entry re\nJOIN lobbyist_identity li ON re.id = li.entry_id\nJOIN address a ON li.address_id = a.id\nJOIN activities_interests ai ON re.id = ai.entry_id\nJOIN field_of_interest foi ON ai.id = foi.activities_id\nJOIN code_label cl ON foi.label_id = cl.id\nWHERE a.city IN (${City:sqlstring})\nGROUP BY cl.de\nORDER BY 2 DESC\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Top Player in dieser Stadt",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n    li.name_text as \"Organisation\",\n    SUM(fe.expenses_to_eur) as \"Budget\"\nFROM register_entry re\nJOIN lobbyist_identity li ON re.id = li.entry_id\nJOIN address a ON li.address_id = a.id\nJOIN financial_expenses fe ON re.id = fe.entry_id\nWHERE a.city IN (${City:sqlstring})\nGROUP BY li.name_text\nORDER BY 2 DESC\nLIMIT 20;"
    }
   ]
  }
 ]
}